name: infinite_calendar_view
description: Easily build your different views of your calendar with this package. Month, week, three days, one day, list ... and many features.
version: 2.5.5
homepage: https://github.com/pickywawa/infinite_calendar_view
issue_tracker: https://github.com/pickywawa/infinite_calendar_view/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sticky_infinite_list: ^4.0.1    # infinite listview for events days list

dev_dependencies:
  lints:
  flutter_test:
    sdk: flutter
